default: &default
  unites_legales:
    - columns: siren
      options:
        unique: true
  etablissements:
    - columns: siren
    - columns: unite_legale_id
    - columns: siret
      options:
        unique: true

development:
  <<: *default

test:
  <<: *default

sandbox:
  <<: *default

production:
  <<: *default
